- name: copy parameters.yml production file
  copy:
    src: "{{ playbook_dir}}/vars/parameters_prod.yml"
    dest: "{{ ansistrano_release_path.stdout }}/app/config/parameters.yml"
#- name: fix symfony cache directory apache ownership
#  file:
#    path: "{{ ansistrano_release_path.stdout }}/app/cache"
#    recurse: no
#    state: directory
#    mode: 0777
