parameters:
#    grupo_local.example.class: SomEnergia\GrupoLocalBundle\Example

services:
#    grupo_local.example:
#        class: %grupo_local.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
