language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - if [[ $TRAVIS_PHP_VERSION = "5.6" ]]; then echo yes | pecl install -f apcu-4.0.11; fi
  - if [[ $TRAVIS_PHP_VERSION = "7.0" ]] || [[ $TRAVIS_PHP_VERSION = "7.1" ]] || [[ $TRAVIS_PHP_VERSION = "7.2" ]]; then echo yes | pecl install -f apcu-5.1.5; fi
  - mysql -e 'create database IF NOT EXISTS symfony;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer selfupdate
  - composer install
  - php app/console doctrine:schema:create --no-interaction --env=test
  - php app/console doctrine:fixtures:load --no-interaction --env=test

script:
  - vendor/phpunit/phpunit/phpunit -c app

notifications:
  email:
    - david@flux.cat

branches:
  only:
    - master
    - devel
