---
- hosts: sw3
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: fix symfony logs directory apache ownership
      file:
        path: "{{ vhost_path }}/shared/app/logs"
        recurse: yes
        mode: 0755
        owner: www-data
        group: www-data
    - name: fix symfony web directory apache ownership
      file:
        path: "{{ vhost_path }}/shared/web"
        recurse: yes
        mode: 0755
        owner: www-data
        group: www-data
    - name: fix symfony cache directory apache ownership
      file:
        path: "{{ vhost_path }}/current/app/cache"
        recurse: yes
        state: directory
        mode: 0755
        owner: www-data
        group: www-data
