---
- hosts: sw3
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: fix symfony logs directory apache ownership
      file:
        path: "{{ ansistrano_deploy_to }}/shared/app/logs"
        recurse: yes
        owner: www-data
        group: www-data
