imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator: ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: [ "twig"]
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        name:       backoffice_session
        handler_id: session.handler.native_file
        save_path:  "%kernel.root_dir%/sessions"
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        admin_version: v1.0.02

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            ApplicationSonataUserBundle: ~
            SonataUserBundle: ~
            FOSUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Genemu Form Select 2 Bundle
genemu_form:
    select2: ~
    date: ~

# Sonata Block
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:   ~
        sonata.block.service.action: ~
        sonata.block.service.rss:    ~
        somenergia.sonata.custom.block.admin_list: ~

# Sonata Admin
sonata_admin:
    title:  'Administrador Som Energia'
    title_logo: '/favicon.png'
    templates:
        layout:     MainBundle:SonataAdmin:somenergia_custom_layout.html.twig
        dashboard:  MainBundle:SonataAdmin:somenergia_custom_dashboard.html.twig
        ajax:       SonataAdminBundle::ajax_layout.html.twig
        list:       SonataAdminBundle:CRUD:list.html.twig
        show:       SonataAdminBundle:CRUD:show.html.twig
        edit:       SonataAdminBundle:CRUD:edit.html.twig
        user_block: MainBundle:SonataAdmin:somenergia_custom_user_block.html.twig
    dashboard:
        blocks:
            - { position: left, type: somenergia.sonata.custom.block.admin_list }
            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Bienvenido al administrador de Som Energia</h2><p>Elige una acción del menú para continuar.</p>" } }
        groups:
            Emails:
            Usuarios:
            Asambleas:
            Socios:
            Grupos locales:

# DIC config
services:
    sonata.users.admin:
        class: Sonata\UserBundle\Admin\Model\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Usuarios, label: Usuario }
        arguments: [null, Application\Sonata\UserBundle\Entity\User, SonataUserBundle:Admin:UserAdmin]
    sonata.groups.admin:
        class: Sonata\UserBundle\Admin\Model\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Usuarios, label: Perfil }
        arguments: [null, Application\Sonata\UserBundle\Entity\Group, SonataUserBundle:Admin:GroupAdmin]
    somenergia.mails.admin:
        class: SomEnergia\MailBundle\Admin\AliasesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Emails, label: Desvíos }
        arguments: [null, SomEnergia\MailBundle\Entity\Aliases, MailBundle:AliasesAdmin]
    somenergia.mailboxes.admin:
        class: SomEnergia\MailBundle\Admin\UsersAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Emails, label: Buzones }
        arguments: [null, SomEnergia\MailBundle\Entity\Users, MailBundle:UsersAdmin]
#    somenergia.asamblea.sede:
#        class: SomEnergia\AsambleaBundle\Admin\SedeAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: Asambleas, label: Sede }
#        arguments: [null, SomEnergia\AsambleaBundle\Entity\Sede, AsambleaBundle:SedeAdmin]
#    somenergia.asamblea.asamblea:
#        class: SomEnergia\AsambleaBundle\Admin\AsambleaAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: Asambleas, label: Asamblea }
#        arguments: [null, SomEnergia\AsambleaBundle\Entity\Asamblea, AsambleaBundle:AsambleaAdmin]
#    somenergia.asamblea.asistencia:
#        class: SomEnergia\AsambleaBundle\Admin\AsistenciaAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: Asambleas, label: Asistencia }
#        arguments: [null, SomEnergia\AsambleaBundle\Entity\Asistencia, AsambleaBundle:AsistenciaAdmin]
    somenergia.socio.socio:
        class: SomEnergia\SocioBundle\Admin\SocioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Socios, label: Socio }
        arguments: [null, SomEnergia\SocioBundle\Entity\Socio, SocioBundle:SocioAdmin]
    somenergia.gruposlocales.cp:
        class: SomEnergia\MainBundle\Admin\CodigoPostalAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Grupos locales, label: Código postal }
        arguments: [null, SomEnergia\MainBundle\Entity\CodigoPostal, MainBundle:CodigoPostalAdmin]
    somenergia.gruposlocales.grupolocal:
        class: SomEnergia\GrupoLocalBundle\Admin\GrupoLocalAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Grupos locales, label: Grupo local }
        arguments: [null, SomEnergia\GrupoLocalBundle\Entity\GrupoLocal, GrupoLocalBundle:GrupoLocalAdmin]
    somenergia.sonata.custom.block.admin_list:
        class: SomEnergia\MainBundle\Block\CustomDashboardBlockService
        arguments: [ "somenergia.sonata.custom.block.admin_list", @templating, @sonata.admin.pool ]
        tags:
            - { name: sonata.block }

# Sonata FOS User
sonata_user:
    security_acl: true
    class:                  # Entity Classes
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

# Friends Of Symfony (FOS)
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  admin
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group

parameters:
    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\UserAdmin
