security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER, ROLE_SONATA_ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
        SONATA:           [ ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT ]
        SOMENERGIA:       [ ROLE_SUPER_ADMINISTRADOR, ROLE_DELEGADO_ASAMBLEA, ROLE_DELEGADO_GRUPO_LOCAL ]
    providers:
        fos_userbundle:
            id: fos_user.user_manager
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            switch_user:        true
            context:            user
            pattern:            /admin(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   /admin/login
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
                use_referer:    true
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:    true
    acl:
        connection: default
    access_control:
        # DMZ
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # SECURED
        - { path: ^/admin/sonata/user, role: ROLE_SUPER_ADMINISTRADOR }
        - { path: ^/admin/somenergia/socio/socio, role: ROLE_DELEGADO_GRUPO_LOCAL }
        - { path: ^/admin/somenergia/socio, role: ROLE_SUPER_ADMINISTRADOR }
        - { path: ^/admin/somenergia/asamblea, role: ROLE_ADMINISTRADOR_ASAMBLEA }
        - { path: ^/admin, role: [ ROLE_USER, ROLE_ADMIN, ROLE_SONATA_ADMIN ] }
        # OPEN
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
