asamblea_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AsambleaBundle:Default:index }

asamblea_asistencia_informes:
    pattern: /admin/somenergia/asamblea/informe/choose
    defaults: { _controller: AsambleaBundle:Informe:choose }