#asamblea_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: AsambleaBundle:Default:index }

asamblea_asistencia_informes:
    pattern: /admin/somenergia/asamblea/informe/choose
    defaults: { _controller: AsambleaBundle:Informe:choose }

asamblea_asistencia_nuevo_registro:
    pattern: /admin/somenergia/asistencia/nuevo
    defaults: { _controller: AsambleaBundle:Asistencia:nuevo }

asamblea_asistencia_registro_seleccionado:
    pattern: /admin/somenergia/asistencia/seleccionado
    defaults: { _controller: AsambleaBundle:Asistencia:seleccionado }