parameters:
#    asamblea.example.class: SomEnergia\AsambleaBundle\Example

services:
#    asamblea.example:
#        class: %asamblea.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
